// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: pel

#include "../ui.h"

// COMPONENT Button1

lv_obj_t * ui_Button1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button1;
    cui_Button1 = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_Button1, 135);
    lv_obj_set_height(cui_Button1, 32);
    lv_obj_set_x(cui_Button1, -91);
    lv_obj_set_y(cui_Button1, -100);
    lv_obj_set_align(cui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_mqtt_label;
    cui_mqtt_label = lv_label_create(cui_Button1);
    lv_obj_set_width(cui_mqtt_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_mqtt_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_mqtt_label, LV_ALIGN_CENTER);
    lv_label_set_text(cui_mqtt_label, "MQTT SETTINGS");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON1_NUM);
    children[UI_COMP_BUTTON1_BUTTON1] = cui_Button1;
    children[UI_COMP_BUTTON1_MQTT_LABEL] = cui_mqtt_label;
    lv_obj_add_event_cb(cui_Button1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Button1_create_hook(cui_Button1);
    return cui_Button1;
}

