// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: pel

#include "../ui.h"

void ui_comp_Back_Button_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Button1_create_hook(lv_obj_t * comp)
{
}
