// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: pel

#ifndef _UI_COMP_BACK_BUTTON_H
#define _UI_COMP_BACK_BUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Back Button
#define UI_COMP_BACK_BUTTON_BACK_BUTTON 0
#define _UI_COMP_BACK_BUTTON_NUM 1
lv_obj_t * ui_Back_Button_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
