// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: pel

#ifndef _PEL_UI_H
#define _PEL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_power(lv_event_t * e);
extern lv_obj_t * ui_power;
extern lv_obj_t * ui_VALUE;
extern lv_obj_t * ui_HEADER;
extern lv_obj_t * ui_tempbar;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_tempval;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_2312321_png);    // assets\2312321.png
LV_IMG_DECLARE(ui_img_4321_png);    // assets\4321.png
LV_IMG_DECLARE(ui_img_1556726307);    // assets\free-icon-keyboard-left-arrow-button-60775.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
